# Generated by Django 5.2.4 on 2025-07-19 12:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('genres', models.CharField(blank=True, max_length=200)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('actors', models.CharField(blank=True, max_length=500)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('plot_keywords', models.CharField(blank=True, max_length=500)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('popularity', models.FloatField(db_index=True, default=0)),
                ('vote_average', models.FloatField(db_index=True, default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('budget', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity', '-vote_average'],
                'indexes': [models.Index(fields=['popularity', 'vote_average'], name='apis_movie_popular_3fef94_idx'), models.Index(fields=['year', 'popularity'], name='apis_movie_year_251f62_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genres', models.CharField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('enable_recommendations', models.BooleanField(default=True)),
                ('recommendation_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='apis_rating_user_id_c85213_idx'), models.Index(fields=['movie', 'rating'], name='apis_rating_movie_i_9d4b5d_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('dislike', 'Dislike'), ('share', 'Share'), ('watchlist_add', 'Added to Watchlist'), ('watchlist_remove', 'Removed from Watchlist')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'interaction_type', 'timestamp'], name='apis_userin_user_id_f39f36_idx'), models.Index(fields=['movie', 'interaction_type'], name='apis_userin_movie_i_078f60_idx')],
            },
        ),
    ]
