services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: sh -c ". /app/.venv/bin/activate && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

